name: 'Corne Build'
on: push
jobs:
  build_colemak_dh:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      layout: 'COLEMAK_DH'
      archive_name: 'colemak_dh_firmware'
  build_colemak:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      layout: 'COLEMAK'
      archive_name: 'colemak_firmware'